### ISSUE TITLE
号直接冻结了，还好是小号

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/docker-wechatbot-webhook#78]

**Comment by danni-cool** [comment]
干了啥事

**Comment by glwhappen** [comment]
啥也没干，就登录还没登录上，登录的时候访问：http://127.0.0.1:3001/loginCheck

返回
{
    "success": false,
    "message": "Unauthorized: Access is denied due to invalid credentials."
}

我尝试了好几次，直接就冻结了，说登录环境异常，让我辅助验证接触，需要找个好友啥的，我还没去弄

**Comment by danni-cool** [comment]
> 啥也没干，就登录还没登录上，登录的时候访问：http://127.0.0.1:3001/loginCheck 
> 返回 { "success": false, "message": "Unauthorized: Access is denied due to invalid credentials." }

这个提示没关系，你访问loginCheck没带token，这个是项目鉴权没过，和微信无关

环境异常就不清楚了

**Comment by glwhappen** [comment]
wxBotWebhook  | 
wxBotWebhook  | AssertionError: 400 != 400
wxBotWebhook  | 
wxBotWebhook  | 配置参数 RECVD_MSG_API: "http://127.0.0.1:8080/receive_msg" <- 不符合 URL 规范, 该 API 将不会收到请求
wxBotWebhook  | 

还有这样的提示，说url不符合规范，为什么呢

**Comment by glwhappen** [comment]
后台代码
```python
import uvicorn

from fastapi import FastAPI, Form

app = FastAPI()


@app.post("/receive_msg")
async def print_json(type: str = Form(), content: str = Form()):
    print(content)
    return {
        "message": "Data received"
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)
```

**Comment by danni-cool** [comment]
https://github.com/danni-cool/docker-wechatbot-webhook/issues/76#issuecomment-1851232242

**Comment by glwhappen** [comment]
```yml
version: '3'
services:
  wxBotWebhook:
    container_name: wxBotWebhook
    image: dannicool/docker-wechatbot-webhook
    environment:
      - RECVD_MSG_API="http://127.0.0.1:8080/receive_msg"
    ports:
      - "3001:3001"
    restart: unless-stopped
```
我就是这么设置的，日志的提示是设置成功了，但是说我的url不符合
> 配置参数 RECVD_MSG_API: "http://127.0.0.1:8080/receive_msg" <- 不符合 URL 规范, 该 API 将不会收到请求
